### todos los productos
GET http://localhost:3000/products/allproducts

### productos fltrados por id
GET http://localhost:3000/products/search/id/722cc0bf-6bde-4d3e-9968-1025a9941a6f


### productos fltrados por nombre
GET http://localhost:3000/products/search/byname?name=milanesa

### crear nuevos productos
POST http://localhost:3000/products/new
Content-Type: application/json

{
    "name": "milanesa napollitana",
    "price": 5.99,
    "description": "doble Tomato y mozzarella",
    "categories": "milanesa"
}
