### todos los productos
GET http://localhost:3000/products/allproducts

### productos fltrados por id
GET http://localhost:3000/products/search/id/722cc0bf-6bde-4d3e-9968-1025a9941a6f 


### productos fltrados por nombre
GET http://localhost:3000/products/search/byname?name=milanesa

### crear nuevos productos
POST http://localhost:3000/products/new
Content-Type: application/json

{
    "name": "milanesa napolitana",
    "image_path": "./public/milanesa.jpg",
    "price": 12.99,
    "description": "milanesa con doble tomate y muzzaralla",
    "categories": ["milanesa", "comida"]
}
